### ISSUE TITLE
Use a logger for output

### ISSUE THREAD

**Issue by currycoder** [gamernetwork/gastatsdash#18]
https://docs.python.org/2/library/logging.html

Currently loads of debug info is printed to stdout which is cluttering up the statsdash log.  Need to be able to configure a logger and be able to configure what level of logging should occur in the config file.

**Comment by fayebutler** [comment]
Definitely would like to implement this, first impressions of what it would do (let me know otherwise): 
each report have a .log file 
with debug info being the run through of where the report is, so if theres an error we can see what website/data/time period caused the problem, e.g. :
-"getting_country_metrics"  would be the function its in? should possibly have what .py file it's in? 
-DEBUG:getting_country_metrics: eurogamer.net for period Jan 2016 
have info when exceptions are caught (i.e. when there is no data for a website time period) e.g. :
-INFO:getting_country_metrics: No data for metabomb: overwatch for period Jan 2015 
and set logging level in the config file to DEBUG or INFO

is this sort of what you meant? anything else i should include?

**Comment by currycoder** [comment]
I think that approach is sound, but maybe just have one .log file, e.g: `/var/log/statsdash/report_generation.log`.  The log format should log each line with a date stamp, which will make it easy enough to search through.

Generally it would be good to refactor out all print statements from the application.  So currently, the cron running on daniels pipes all printed output to `/var/log/statsdash/scheduler.log` - it would be better to just set this as a schedule logger and change the print statements to log statements.

**Comment by fayebutler** [comment]
yes definitely, sounds good!
